package io.github.sdxqw.miniblock.sprite;

public enum TextureID {
    DIRT, GRASS, AIR,

    MINIPLANT1, MINIPLANT2, MINIPLANT3,

    IDLE0, IDLE1, IDLE2, IDLE3, IDLE4, IDLE5,

    IDLE0_BEHIND, IDLE1_BEHIND, IDLE2_BEHIND, IDLE3_BEHIND, IDLE4_BEHIND, IDLE5_BEHIND,

    IDLE0_RIGHT, IDLE1_RIGHT, IDLE2_RIGHT, IDLE3_RIGHT, IDLE4_RIGHT, IDLE5_RIGHT,

    IDLE0_LEFT, IDLE1_LEFT, IDLE2_LEFT, IDLE3_LEFT, IDLE4_LEFT, IDLE5_LEFT,
}
